
workflows:
  build-android:
    name: Build APK Admin e Guest
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Pulizia
        script: flutter clean
      - name: Ottieni dipendenze
        script: flutter pub get
      - name: Build Admin APK
        script: flutter build apk --release -t lib/main_admin.dart
      - name: Build Guest APK
        script: flutter build apk --release -t lib/main_guest.dart
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
